import { Github, FileVideo, UploadCloud, Activity } from "lucide-react";
import { Button } from "./components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "./components/ui/textarea";
import { Label } from "./components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./components/ui/select";
import { Slider } from "./components/ui/slider";

export function App() {
  return (
    <div className="min-h-screen flex flex-col">
      {/** Header */}
        <div className="px-6 py-4 flex items-center justify-between border-b">

          <h1 className="text-xl font-extrabold">Upload-IA</h1>

          <div className="flex items-center gap-4">
            <span className="text-sm text-slate-400">Developed on Rocketseat NLW 🚀🚀</span>

            <Separator orientation="vertical" className="h-6 w-0.5 bg-slate-700"/>
            
            <Button variant="secondary">
              <Github className="w-6 h-6 p-0" />
            </Button>
          </div>
        </div>

        <main className="flex flex-1 p-6 gap-6">
          <section className="flex flex-col flex-1">
            
            <div className="grid grid-rows-2 gap-4 flex-1">
              <Textarea 
              className="resize-none p-4 leading-relaxed"
              placeholder="Include the Prompt for IA"
              />
              <Textarea 
              className="resize-none p-4 leading-relaxed"
              placeholder="Result Generated by IA"
               readOnly
               />
            </div>

            <p className="text-sm text-slate-400">
              Remember you can use the variable <code className="text-violet-500">{'{transcription}'}</code> at your prompt to add the transcript content of slected video
              </p>
          </section>

          <aside className="w-80 space-y-6">
            <form action="" method="post" className="space-y-4">
              <label 
              htmlFor="video"
              className="border-8 border-double flex flex-col rounded-md aspect-video items-center justify-center cursor-pointer text-3xl font-semibold text-slate-400 hover:bg-slate-800"
              >
                <FileVideo/>
                Upload Video
              </label>
              <input type="file" id="video" accept="video/mp4" className="sr-only"/>
              <Separator/>

              <div className="space-y-2">
                <Label htmlFor="TranscriptionPrompt" className="font-mono">Transcription Prompt</Label>
                <Textarea 
                id="TranscriptionPrompt" 
                className="leading-relaxed h-20 resize-none"
                placeholder="include keywords mentioned in the video separated by comma"
                />
              </div>

              <Button type="submit" className="w-full">
                Upload Video
                <UploadCloud className=" ml-2"/>
              </Button>
            </form>
            <Separator/>
            <form action="" method="post" className="space-y-6">

              <div className="space-y-2">
                <Label>Prompt</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="Select Prompt"/>
                    <SelectContent>
                      <SelectItem value="title">YouTube Title</SelectItem>
                      <SelectItem value="description">YouTube Description</SelectItem>
                    </SelectContent>
                  </SelectTrigger>
                </Select>
              </div>
              

              <div className="space-y-2">
                <Label>Model</Label>
                <Select disabled defaultValue="GPT3">
                  <SelectTrigger>
                    <SelectValue/>
                    <SelectContent>
                      <SelectItem value="GPT3">GPT3</SelectItem>
                    </SelectContent>
                  </SelectTrigger>
                </Select>
                <span className="block text-xs italic text-slate-300">
                  You can Customize this option later
                </span>
              </div>
              
              <Separator/>

              <div className="space-y-4">
                <Label>Temperature</Label>
                <Slider
                min={0}
                max={2}
                step={0.2}
                />
                <span className="block text-xs italic text-slate-300 leading-relaxed">
                  high values will give you more creative results
                </span>
              </div>
              <Separator/>

              <Button type="submit" className="w-full font-bold">
                RUN
                <Activity className="ml-2 w-5"/>
              </Button>
            </form>
          </aside>

        </main>
    </div>
  )
}